// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mail} from '../models';

export function GetEmailBody(arg1:string,arg2:number):Promise<string>;

export function GetEmailsForMailbox(arg1:string):Promise<Array<mail.SerializableMessage>>;

export function GetMailboxes():Promise<Array<string>>;

export function IsLoggedIn():Promise<boolean>;

export function LoginUser(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function LoginUserWithOAuth(arg1:string):Promise<boolean>;

export function LogoutUser():Promise<void>;

export function StartOAuth(arg1:string):Promise<void>;
