// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountIds() {
  return window['go']['wails_app']['App']['GetAccountIds']();
}

export function GetEmailBody(arg1, arg2, arg3) {
  return window['go']['wails_app']['App']['GetEmailBody'](arg1, arg2, arg3);
}

export function GetEmailsForMailbox(arg1, arg2, arg3, arg4) {
  return window['go']['wails_app']['App']['GetEmailsForMailbox'](arg1, arg2, arg3, arg4);
}

export function GetMailboxes(arg1) {
  return window['go']['wails_app']['App']['GetMailboxes'](arg1);
}

export function IsLoggedIn(arg1) {
  return window['go']['wails_app']['App']['IsLoggedIn'](arg1);
}

export function LoginUser(arg1, arg2, arg3) {
  return window['go']['wails_app']['App']['LoginUser'](arg1, arg2, arg3);
}

export function LoginUserWithOAuth(arg1) {
  return window['go']['wails_app']['App']['LoginUserWithOAuth'](arg1);
}

export function LogoutUser(arg1) {
  return window['go']['wails_app']['App']['LogoutUser'](arg1);
}

export function StartOAuth(arg1) {
  return window['go']['wails_app']['App']['StartOAuth'](arg1);
}

export function UpdateMailboxes(arg1) {
  return window['go']['wails_app']['App']['UpdateMailboxes'](arg1);
}

export function UpdateMessages(arg1, arg2) {
  return window['go']['wails_app']['App']['UpdateMessages'](arg1, arg2);
}
