// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmailBody(arg1, arg2) {
  return window['go']['wails_app']['App']['GetEmailBody'](arg1, arg2);
}

export function GetEmailsForMailbox(arg1) {
  return window['go']['wails_app']['App']['GetEmailsForMailbox'](arg1);
}

export function GetMailboxes() {
  return window['go']['wails_app']['App']['GetMailboxes']();
}

export function IsLoggedIn() {
  return window['go']['wails_app']['App']['IsLoggedIn']();
}

export function LoginUser(arg1, arg2, arg3) {
  return window['go']['wails_app']['App']['LoginUser'](arg1, arg2, arg3);
}

export function LoginUserWithOAuth(arg1) {
  return window['go']['wails_app']['App']['LoginUserWithOAuth'](arg1);
}

export function LogoutUser() {
  return window['go']['wails_app']['App']['LogoutUser']();
}

export function StartOAuth(arg1) {
  return window['go']['wails_app']['App']['StartOAuth'](arg1);
}
