// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmailBody(arg1, arg2) {
  return window['go']['main']['App']['GetEmailBody'](arg1, arg2);
}

export function GetEmailsForMailbox(arg1) {
  return window['go']['main']['App']['GetEmailsForMailbox'](arg1);
}

export function GetMailboxes() {
  return window['go']['main']['App']['GetMailboxes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoginUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2, arg3);
}

export function LogoutUser() {
  return window['go']['main']['App']['LogoutUser']();
}
